---
title: ''
output: 
    bookdown::word_document2: 
      reference_docx: word-styles-reference.docx #make sure this line is indented! see this guide for formatting: https://rmarkdown.rstudio.com/articles_docx.html
bibliography: references.bib
csl: new-phytologist.csl

---


```{r eval = TRUE, echo=FALSE, warning=FALSE, results='hide'}
#Tables
table_pools =1
table_variables =2
table_recommendations = 3

#Figures
fig_variable_mapping=1
fig_map=2
fig_histograms=3


#Appendices
appendix_ForC_updates = "Methods S1"
appendix_IPCC_definitions = "Notes S1"
table_ForCchanges = "Table S1"
table_ForCfieldmapping = "Table S2"

#READING IN FILES TO GET FIGURES/ TABLES/ STATS 
path_to_dir <- dirname(dirname(getwd())) # get path to repo 
path_to_ForC= "/Users/kteixeira/Dropbox (Smithsonian)/GitHub/ForC-db" #Krista's laptop
# path_to_ForC= "/Users/kteixeira/Dropbox (Smithsonian)/GitHub/ForC-db" #Madison, to knit, you'll need to enter the path to ForC-db on your computer, then un-comment this line.

# MOVE FIGURE FILES 
#world map from GitHub
do.call(file.remove, list(list.files(paste0(path_to_dir, "/doc/manuscript/figures_tables"), "World_Map_of_sites_with_FAO_and_IPCC_data_sent.png", full.names = TRUE))) # first remove old file
flist <- list.files(paste0(path_to_ForC, "/ForC/figures/"), "World_Map_of_sites_with_FAO_and_IPCC_data_sent.png", full.names = TRUE)
file.copy(flist, paste0(path_to_dir, "/doc/manuscript/figures_tables"))


#Statistics
ForC_measurements <- read.csv(paste0(path_to_ForC,"/ForC/data/ForC_measurements.csv"), stringsAsFactors = FALSE, check.names = FALSE)
n_records_ForC= length(ForC_measurements[,"measurement.ID"])  # total n records in ForC

ForC_plots <- read.csv(paste0(path_to_ForC,"/ForC/data/ForC_plots.csv"), stringsAsFactors = FALSE, check.names = FALSE)
n_plots_ForC = length(ForC_plots[,"plot.ID"]) # total n plots in ForC

ForC_sites <- read.csv(paste0(path_to_ForC,"/ForC/data/ForC_sites.csv"), stringsAsFactors = FALSE, check.names = FALSE)
n_areas_ForC = max(ForC_sites$geographic.area, na.rm = TRUE) # total n geographic areas in ForC

ForC_simplified <- read.csv(paste0(path_to_ForC,"/ForC/ForC_simplified/ForC_simplified.csv"), stringsAsFactors = FALSE, check.names = FALSE)
n_independent_records_ForC= length(ForC_simplified[,"measurement.ID"]) #suspected duplicates removed. This is the number of records fin ForC simplified.

C_variables <- read.csv(paste0(path_to_dir,"/doc/manuscript/figures_tables/C_variables.csv"), stringsAsFactors = FALSE, check.names = FALSE)
n_relevant_variables = nrow(C_variables) - 8  # n variables relevant = rows in C_variables - headers and total 
n_relevant_variables_with_no_data =  sum(C_variables$`n in ForC` == 0,  na.rm = TRUE)
n_relevant_variables_with_data= n_relevant_variables - n_relevant_variables_with_no_data


n_ind_records_EFDB_variables= C_variables[length(C_variables[,"variable"]), "n independent records in ForC"] #n independent records relevant to EFDB
n_ind_records_agb <- C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass_ag"]
n_ind_records_agb_components <- C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass_ag_woody"] + C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass_ag_foliage"]
n_ind_records_biomass <- C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass"]
n_ind_records_rootbiomass <- C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass_root"] +C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass_root_fine"]+C_variables$`n independent records in ForC`[C_variables$`variable` == "biomass_root_coarse"]
n_ind_records_deadwood <- C_variables$`n independent records in ForC`[C_variables$`variable` == "deadwood"] +C_variables$`n independent records in ForC`[C_variables$`variable` == "deadwood_down"]+C_variables$`n independent records in ForC`[C_variables$`variable` == "deadwood_standing"]
n_ind_records_OL <- C_variables$`n independent records in ForC`[C_variables$`variable` == "litter"] +C_variables$`n independent records in ForC`[C_variables$`variable` == "O.horizon"]
n_ind_records_TotEcosystemC <- C_variables$`n independent records in ForC`[C_variables$`variable` == "total.ecosystem_2"] 
n_ind_records_SOC <- C_variables$`n independent records in ForC`[C_variables$`variable` == "SOM / SOC"] 
n_ind_records_deltaagb <- C_variables$`n independent records in ForC`[C_variables$`variable` == "delta.agb"] 
n_ind_records_deltaOL <- C_variables$`n independent records in ForC`[C_variables$`variable` == "delta.O.horizon"] 
flux_variables_with_records <- c("NPP_woody", "ANPP_woody", "ANPP_woody_stem", "ANPP_woody_branch", "woody.mortality_ag", "BNPP_root", "BNPP_root_fine","BNPP_root.turnover_fine","BNPP_root_coarse" , "ANPP_litterfall", "NPP_litter", "R_het_litter")
n_ind_records_flux <- sum(C_variables$`n independent records in ForC`[C_variables$`variable` %in% flux_variables_with_records])

n_records_reviewed_or_added= C_variables[length(C_variables[,"variable"]), "n reviewed"]
n_records_added = max(ForC_measurements$measurement.ID) -48956 # Madison's entries start with measurement.ID = 48956
n_records_checked = n_records_reviewed_or_added - n_records_added # this will be hard to get at, but we can at least estimate a minimum (= previously existing records in records sent to EFDB)


n_records_sent_to_EFDB = C_variables[length(C_variables[,"variable"]), "n submitted to EFDB"] # n records sent to EFDB
n_relevant_variables_no_records_sent =  sum(C_variables$`n submitted to EFDB` == 0,  na.rm = TRUE)
n_relevant_variables_records_sent= n_relevant_variables - n_relevant_variables_no_records_sent
n_records_sent_biomass<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass"]
n_records_sent_agb <- C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass_ag"]
n_records_sent_agb_components <- C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass_ag_woody"] + C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass_ag_foliage"]
n_records_sent_rootbiomass <- C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass_root"] 
n_records_sent_rootbiomass_components <- C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass_root_fine"]+C_variables$`n submitted to EFDB`[C_variables$`variable` == "biomass_root_coarse"]
n_records_sent_deadwood<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "deadwood"] 
n_records_sent_deadwood_components<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "deadwood_down"]+C_variables$`n submitted to EFDB`[C_variables$`variable` == "deadwood_standing"]
n_records_sent_litter<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "litter"] +C_variables$`n submitted to EFDB`[C_variables$`variable` == "O.horizon"]
n_records_sent_soil<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "SOM / SOC"] 
n_records_sent_stocks = n_records_sent_biomass+n_records_sent_agb+n_records_sent_agb_components+n_records_sent_rootbiomass+n_records_sent_rootbiomass_components+n_records_sent_deadwood+n_records_sent_deadwood_components+ n_records_sent_litter+ n_records_sent_soil
n_records_sent_delta.agb<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "delta.agb"]
n_records_sent_delta.litter<- C_variables$`n submitted to EFDB`[C_variables$`variable` == "delta.O.horizon"]+C_variables$`n submitted to EFDB`[C_variables$`variable` == "delta.litter"]
n_records_sent_increments <- n_records_sent_delta.agb+n_records_sent_delta.litter
n_records_sent_fluxes <- sum(C_variables$`n submitted to EFDB`[C_variables$`variable` %in% flux_variables_with_records])
n_records_sent_fluxes_check = n_records_sent_to_EFDB-n_records_sent_stocks-n_records_sent_increments


n_records_posted_EFDB = 376 # n records accepted and posted in EFDB (easy to determine by entering "ForC" in the "Other Properties" search field of EFDB: https://www.ipcc-nggip.iges.or.jp/EFDB/find_ef.php. Then get number from upper left box where it says "displayed records")

n_new_variables = 11 + 2 + 2 #delta. + woody.mortality + O horizon
# get n fields modified
sampling_details <- read.csv(paste0(path_to_ForC,"/ForC/database_management_records/record_of_changes.csv"), stringsAsFactors = FALSE, check.names = FALSE)
n_fields_modified =  length(sampling_details[,"Column"]) + 4 


```




# `r appendix_ForC_updates`. Updates to ForC (ForC v4.0) {-}

Here, we describe changes relative to ForC v3.0 [@anderson-teixeira_carbon_2021], which were implemented prior to the release of ForC v4.0.

## New or modified fields {-}

We added or modified a total of `r n_fields_modified` fields (`r table_ForCchanges`).
Most notably, these included improvement of the representation of uncertainty, recording of original units and organic matter to C conversion factors, and expanding the information recorded in the citations table. 
For the latter, we used an R script to automatically harvest (scrape) the URL, citation, abstract and language of the publications, based on their DOI, using R package `rvest`[@wickham_rvest_2022]. 
That information was manually retrieved when the web scraping failed. 

## New variables {-}

To create structure for EFDB-relevant records, we added a total of `r n_new_variables` new variables to the set of named and defined variables, counting each pair of variables with units in C (ending in  `_C`) or organic matter (ending in `_OM`) as one. 
The majority of these were increment variables (n=11), adding to only one previously defined increment variable (aboveground biomass increment, *delta.agb*). 
These are directly related to C stocks as previously defined in ForC, with "*delta.*" added in front of the variable name.
Further, we added variables capturing the belowground component of woody mortality (*woody.mortality_root*) and the combined aboveground and belowground components of woody mortality (*woody.mortality*).
Although most of these variables lacked records in ForC as of `r format(Sys.time(), '%B %d, %Y')`, their addition gave the structure such that records can be populated over time. 
Finally, to provide better definition of the previously existing variable *organic.layer*, which has a nebulous definition that reflects the varied definitions adopted by original studies, we added two clearly defined variables: *litter* (relatively undecomposed plant material/ OL horizon), and *O.horizon* (entire O-horizon, including OL).




## Quality control measures {-}
Prior to releasing ForC v4.0, we executed several quality control measures.
First, we implemented a system of continuous integration using GitHub Actions [*sensu* @kim_implementing_2022] to run some automatic checks any time the master data files are updated, including outlier tests and checks for completeness and naming consistency of records across data files.
Second, to improve information on geographic coordinates, we created a field to record coordinate precision (`r table_ForCchanges`), and flagged and reviewed records with suspected low precision.
Third, to identify erroneous climate data, we compared ForC climate values to those extracted from WorldClim version 2.1 [@vandepol_identifying_2016; @bailey_climwin_2016] based on site coordinates. 
Records deviating from WorldClim values by more variable-specific thresholds (>5°C for mean annual temperature, >7.5°C for mean temperatures of the warmest and coldest months, or >1 for log(mean annual precipitation in mm)) were flagged as requiring review prior to use in analysis or submission to EFDB.

Because ForC v4.0 contained known duplicate records, we used R scripts to identify likely duplicates, as detailed in @anderson-teixeira_carbon_2021.
Henceforth, we refer to the set of records with likely duplicates removed as "independent records".
All records sent to EFDB were ensured to be independent and original through manual review, as detailed below.

## Manual review of records to be sent to EFDB {-}

EFDB data submissions required information that was not recorded in previous versions of ForC, but for which new fields were created for EFDB compatibility (`r table_ForCchanges`).
It was therefore necessary to return to original publications to retrieve relevant information, including 
(1) estimates in original units, 
(2) confidence intervals (when not already in ForC),
(3) whether records of interest were presented in tables or text or digitized from figures (EFDB will not accept digitized data), 
(4) whether records of interest were presented directly, as opposed to having been calculated from related variables (for example, if a study presents aboveground biomass and root biomass but not total biomass, EFDB would not accept the sum of these as a valid record of total biomass)
We also checked that existing ForC records were complete and correct.

Manual review of records was the limiting step for data submission to EFDB. 
We prioritized review of
(1) records from the Forest Global Earth Observatory [ForestGEO, @anderson-teixeira_ctfsforestgeo_2015; @davies_forestgeo_2021],
(2) studies with confidence intervals recorded in ForC (because uncertainty estimates are important to the IPCC),
(3) original publications containing large numbers of EFDB-relevant records,
and (4) records from tropical regions.
The latter criteria was motivated by the fact that although tropical forest is the single most important biome for climate change mitigation [@griscom_natural_2017;@griscom_national_2020], ground-based data on tropical forest C cycling tends to be more scarce due to a variety of challenges [@anderson-teixeira_carbon_2021; @delima_making_2022], and tropical countries are more likely to apply Tier 1 methodology that bases forest C budgets on internationally defined IPCC default values [@romijn_assessing_2015].

## Addition of new records {-}

In addition to reviewing existing records, we added a total of `r n_records_added` new records to ForC.
These included 104 records<!--100 from Piponiot, 4 from Lutz--> from two studies [@piponiot_distribution_2022; @lutz_largediameter_2021] that were not previously included in ForC.
In addition, we created new records for `r n_records_added-104` EFDB-relevant estimates presented in the original publication that were not yet present in ForC.



## References

