---
title: ''
output: 
    bookdown::word_document2: 
      reference_docx: word-styles-reference.docx #make sure this line is indented! see this guide for formatting: https://rmarkdown.rstudio.com/articles_docx.html
bibliography: references.bib
csl: new-phytologist.csl

---

```{r eval = TRUE, echo=FALSE, warning=FALSE, results='hide'}
#Tables
table_pools =1



#Appendices
appendix_ForC_updates = "Methods S1"
appendix_IPCC_definitions = "Notes S1"
table_ForCchanges = "Table S1"
table_ForCfieldmapping = "Table S2"


```



# `r appendix_IPCC_definitions`. Summary of IPCC methods and definitions for forests {-}


The end goal of IPCC greenhouse gas inventories is to quantify greenhouse gas emissions to, or withdrawals from, the atmosphere on an annual basis, most commonly on a national level [@ipcc_2006_2006;@ipcc_2019_2019]. 
For each stratum of subdivision within a land-use category, annual stock changes ($\Delta C$; t C yr^-1^) are calculated as the sum of changes in various pools (see **Carbon Pools** section below), plus any harvested wood products.
Thus, C cycle variables relevant to the IPCC methodology and to EFDB include C stocks, net annual increments, and fluxes in the IPCC-defined pools.


## Carbon Pools {-}

Forest ecosystem C pools may be parsed in various ways, and while certain definitions and thresholds are more common than others, there is no single standard for measuring or reporting that is adhered to by all -- or even most -- scientific studies. 
IPCC parses forest C pools into biomass (aboveground and belowground), dead organic matter (dead wood and litter), and soil organic matter (Table `r table_pools`).
While there is some flexibility around the components included in each pool, each national inventory must apply these in a consistent manner.


### Biomass {-}
Biomass includes living vegetation, above- and below-ground, both woody and herbaceous, but with a focus on woody plants and trees given their much greater potential to sequester large amounts of C [@ipcc_2006_2006].

Aboveground biomass, which is typically <200 t C ha^-1^ but can exceed 700 t C ha^-1^ [@anderson-teixeira_carbon_2021], is defined by the IPCC as "all biomass of living vegetation above the soil including stems, stumps, branches, bark, seeds, and foliage" [@ipcc_good_2003;@ipcc_2006_2006].
IPCC's guidance is that the understory may be excluded if it constitutes a "minor" component [defined as < 25 - 30 % of emissions/removals for the overall category, @ipcc_2006_2006], and where a commonly applied minimum size sampling threshold for mature forests would be 10 cm stem diameter at breast height (DBH).
A recent study characterizing the contributions of trees in different DBH classes to ecosystem C stocks and fluxes found that trees 1 - 10 cm DBH contributed up to ~8% aboveground biomass, ~17% aboveground woody net primary productivity ($ANPP_{woody.stem}$), and ~20% woody mortality ($M_{woody}$) of mature closed-canopy forests worldwide [@piponiot_distribution_2022], and therefore stems < 10 cm DBH can usually be considered a minor component of aboveground biomass for these forests.
In regrowth forests, woodlands, or savannas, small trees and shrubs contribute a much larger proportion of C stocks and fluxes [@lutz_global_2018; @piponiot_distribution_2022; @hughes_biomass_1999], and, correspondingly, biomass estimates for these ecosystems tend include smaller size classes. 
While IPCC guidance specifies that all living vegetation should be included in biomass estimates, forest censuses and biomass estimates do not consistently include life forms other than dicot trees (e.g., lianas, ferns, palms, bamboo), although these do tend to be censused when they constitute a large proportion of the biomass [e.g., @fukushima_recovery_2007].
Further, it is important to note that the IPCC definition of aboveground biomass excludes standing dead wood, which is included in remote sensing biomass estimates [@duncanson_aboveground_2021].

A universal challenge in estimating biomass (living or dead) from forest census data is applying appropriate allometric models to convert DBH measurements to biomass, and such selection has an enormous influence on estimates of biomass stocks, increments, and fluxes [@clark_landscapescale_2000;@clark_net_2001;@calders_laser_2022].
While trusted and standardized allometric models are becoming increasingly available [@chave_improved_2014;@rejou-mechain_biomass_2017;@gonzalez-akre_allodb_2022], large uncertainties remain.
IPCC Tier 1 values currently draw on studies applying a variety of allometric models [e.g., @requenasuarez_estimating_2019; @rozendaal_aboveground_2022].

Belowground biomass is defined as "all biomass of live roots" [@ipcc_good_2003;@ipcc_2006_2006], a definition including both coarse roots, whose biomass is typically estimated based on stem censuses and allometries or belowground to aboveground biomass ratios, and fine roots, whose biomass is typically estimated via extraction of roots from soil samples.
The former, which is typically <40 t C ha^-1^ [@anderson-teixeira_carbon_2021], is methodologically linked to aboveground biomass estimates, sharing the same methodological sources of variation, and tending to be very uncertain [e.g., @keller_biomass_2001].
Fine root biomass generally constitutes a much smaller C pool [typically <5 t C ha^-1^, @anderson-teixeira_carbon_2021], and IPCC guidance is that it can be excluded when fine roots cannot be distinguished empirically from soil organic matter or litter [@ipcc_2006_2006], which can be a painstaking process. 
Field methods for estimating root biomass are highly variable [@freschet_starting_2021].
IPCC's default method for Tier 1 estimates is to apply a ratio of belowground to aboveground biomass, with default factors defined based on ecological zone, continent, and forest age<!--IPCC table 4.4--> [@ipcc_2006_2006;@ipcc_2019_2019].

### Dead Organic Matter {-}

Dead organic matter includes all non-living biomass larger than the litter size threshold. 
Its inclusion in inventories is not required under Tier 1 methodology for Forest Land remaining Forest Land (see **Land Classification** section below), but is required for land that has transitioned to or from forest within the past 20 years [@ipcc_2006_2006].

Dead wood, which is typically <50 t C ha^-1^ but can exceed 150 t C ha^-1^ [@anderson-teixeira_carbon_2021], is defined by IPCC as "all non-living woody biomass not contained in the litter, either standing, lying on the ground, or in the soil" [@ipcc_good_2003;@ipcc_2006_2006]. 
This pool includes standing and fallen dead wood, stumps, and dead roots of diameter ≥10 cm (or a diameter specified by the country).
Dead wood stocks and fluxes can be quite variable across forests [@anderson-teixeira_carbon_2021], and can at times be the dominant pool in a forest ecosystem [e.g., following a severe natural disturbance, @carmona_coarse_2002].
However, aboveground dead wood remains relatively poorly characterized at a global scale [@anderson-teixeira_carbon_2021], and belowground dead wood is rarely studied [@merganicova_dadwood_2012].
In turn, dead wood pools are poorly characterized in large-scale forest C budgets [@pan_large_2011;@harris_global_2021], and IPCC's latest Tier 1 default values are based on just 1-31 references per climate zone [Table 2.2 in @ipcc_2019_2019].<!--table 2.2-->

Litter, which is typically <40 t C ha^-1^ but can exceed 100 t C ha^-1^ [@anderson-teixeira_carbon_2021], is defined by IPCC as including "all non-living  biomass  with  a  diameter  less  than  a  minimum  diameter  chosen  by  the  country  (for  example 10 cm), lying dead, in various states of decomposition above the mineral or organic soil" [@ipcc_good_2003;@ipcc_2006_2006].
As noted above, live fine roots may be included in litter when difficult to separate empirically.
The definition includes the entire O horizon, including litter (OL), fumic (OF), and humic (OH) layers, in addition to litter embedded within the soil.
This definition contrasts with empirical studies that focus on aboveground litter, often including only the OL layer in the definition of litter, and do not always specify the components included.
Similar to dead wood, litter is poorly characterized in large-scale forest C budgets [@pan_large_2011;@harris_global_2021], and IPCC's latest Tier 1 default values are based on just 1-7 references per climate zone [Table 2.2 in @ipcc_2019_2019].<!--table 2.2-->

### Soil Organic Matter/ Carbon {-}

Soil organic matter/ carbon (SOM/ SOC), which is typically >100 t C and can exceed 300 t C in the top two meters of soil [@sanderman_soil_2017], is defined by IPCC as "organic carbon in mineral and organic soils (including peat) to a specified depth chosen by the country and applied consistently through the time series" [@ipcc_good_2003;@ipcc_2006_2006]. 
Live fine roots may be included with soil organic matter when it is not feasible to distinguish them empirically.
The greatest source of methodological variation in measuring SOM/ SOC is sampling depth, which has a suggested default of 30 cm but may vary by country provided that consistent criteria are applied. 

## Land classification {-}
IPCC defines land-use categories to include six categories -- Forest Land, Grassland, Wetlands, Cropland, Settlements, and Other Land [@ipcc_2006_2006].
Sub-divisions include land that has remained in a particular category for >20 years (e.g., Forest Land remaining Forest Land) and land that has been converted from one category to another in the past 20 years (e.g., Cropland converted to Forest Land). 
Forest Land is defined as at least 10-30% crown cover of trees with potential to reach a minimum height of 2-5 m *in situ*, and shorter-stature natural vegetation would be classified as Grassland [@ipcc_good_2003].
Definitions of forest are allowed to vary by country, but must be applied consistently.
Forest Land includes land where vegetation temporarily falls below the threshold values for forest (e.g., due to disturbance), but is expected to exceed those thresholds in the future [@ipcc_good_2003].

The UNFCCC requires greenhouse gas reporting for all managed lands in a country, where management is defined as "human interventions and practices have been applied to perform production, ecological or social functions" [@ipcc_2006_2006]. 
This expansive definition of managed land implies that the majority of Forest Land in most countries is managed.
However, the definition is applied differently across countries, and the majority of governments have yet to report their approach for defining managed land or provide maps of managed land [@ogle_delineating_2018; @deng_comparing_2021].


## References {-}

